set -g mouse on
set -g default-terminal "tmux-256color" # support color in tmux session
set -ag terminal-overrides ",xterm-256color:RGB" # support color in parent terminal when using programs like vim

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# tpm plugin
set-environment -g TMUX_PLUGIN_MANAGER_PATH ~/.config/tmux/plugins
set -g @plugin 'tmux-plugins/tpm' # https://github.com/tmux-plugins/tpm/blob/master/README.md

# list of tmux plugins
set -g @plugin 'tmux-plugins/tmux-sensible' # Basic tmux settings everyone can agree on https://github.com/tmux-plugins/tmux-sensible
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart https://github.com/tmux-plugins/tmux-resurrect
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes https://github.com/tmux-plugins/tmux-continuum

set -g @resurrect-capture-pane-contents 'on' # allow tmux-ressurect to capture pane contents
set -g @continuum-restore 'on' # enable tmux-continuum functionality

# https://github.com/tmux-plugins/tpm/blob/master/docs/automatic_tpm_installation.md
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'